import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')
from Autodesk.Revit.DB import *

# 获取当前文档
doc = doc = __revit__.ActiveUIDocument.Document

# 获取项目基点
project_base_point = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_ProjectBasePoint).FirstElement()

# 打印项目基点的坐标
p_base_point = project_base_point.get_BoundingBox(None).Min
print("Project Base Point Location: X: {0}, Y: {1}, Z: {2}".format(p_base_point.X, p_base_point.Y, p_base_point.Z))

# 开启事务
TransactionManager.Instance.EnsureInTransaction(doc)

# 设置项目基点的新坐标
new_x = 100.0
new_y = 200.0
new_z = 0.0
project_base_point.get_Parameter(BuiltInParameter.BASEPOINT_EASTWEST_PARAM).Set(new_x)
project_base_point.get_Parameter(BuiltInParameter.BASEPOINT_NORTHSOUTH_PARAM).Set(new_y)
project_base_point.get_Parameter(BuiltInParameter.BASEPOINT_ELEVATION_PARAM).Set(new_z)

# 提交事务
TransactionManager.Instance.TransactionTaskDone()